data:
    data_dir:              ./data
    raw:
        midi:              ./data/raw/midi
        metadata:          ./data/raw/metadata
    processed_dir:         ./data/processed
    processed:
        analysis:          ./data/processed/analysis
        cleaned:          ./data/processed/cleaned
    prepared_dir:          ./data/prepared
    prepared:
        train:             ./data/prepared/train
        train_data:        ./data/prepared/train.pkl
        val:               ./data/prepared/valid
        val_data:          ./data/prepared/valid.pkl
 
    max_bars:             8
    grids_per_bar:        32

    train_ratio:          0.9
    val_ratio:            0.1          

model:
    n_head:              8
    d_model:             128
    d_ff:                2048
    num_layers:          6
    max_seq_len:         1400
    vocab_size:          181 
    dropout:             0.1

training:
    lr:               0.0005
    batch_size:       16
    max_epochs:       10
    experiments_dir:   ./experiments

    max_lr:           1.0e-4
    min_lr:           5.0e-6
    lr_decay_steps:   150000    
    ckpt_dir:         ./ckpt/enc_dec_12L-16_bars-seqlen_1280
    trained_steps:    0
    lr_warmup_steps:  200
    no_kl_steps:      10000
    kl_cycle_steps:   5000
    kl_max_beta:      1.0
    free_bit_lambda:  0.25
    constant_kl:      False
    ckpt_interval:    50
    log_interval:     10
    val_interval:     50

generate:
    temperature:                0.7
    max_input_dec_seqlen:       1024     # should be set to equal to or less than `dec_seqlen` used during training