data:
    data_dir:              ./data
    raw:
        midi:              ./data/raw/midi
        metadata:          ./data/raw/metadata
    processed_dir:         ./data/processed
    processed:
        analysis:          ./data/processed/analysis
        cleaned:          ./data/processed/cleaned
    prepared_dir:          ./data/prepared
    prepared:
        train:             ./data/prepared/train
        train_data:        ./data/prepared/train.pkl
        val:               ./data/prepared/valid
        val_data:          ./data/prepared/valid.pkl
 
    max_bars:             8
    grids_per_bar:        32

    train_ratio:          0.9
    val_ratio:            0.1          

model:
    n_head:              8
    d_model:             128
    d_ff:                512
    num_layers:          6
    max_seq_len:         1400
    vocab_size:          181 
    dropout:             0.3

training:
    lr:                             0.0005
    batch_size:                     24
    max_epochs:                     20
    experiments_dir:                ./experiments
    gradient_accumulation_steps:    2
    patience:                       8
    warmup_proportion:              0.1
    min_lr:                         0.00001
    max_grad_norm:                  1.0
    weight_decay:                   0.005

generate:
    temperature:                0.7
    max_seqlen:                 1300